### ISSUE TITLE
Chapter 5, page 79

### ISSUE THREAD

**Issue by miltar** [Apress/learn-android-studio-3#1]
Hi Ted:
Inside onCreate method you reference to a nonexistent ButtonListener class.
Thanks. 
Great book!

**Comment by miltar** [comment]
I made use of:
```java
      Button btn1 = (Button) findViewById(R.id.button1);
      Button btn2 = (Button) findViewById(R.id.button2);
      Button btn3 = (Button) findViewById(R.id.button3);

      btn1.setOnClickListener(this);
      btn2.setOnClickListener(this);
      btn3.setOnClickListener(this);
```
it is correct?

**Comment by AndreasMenz** [comment]
Not sure if it's correct (I'm new to Android) but I chose the same solution and it works.

**Comment by miltar** [comment]
Hi Andreas...
I think the same, since MainActivity (this) acts as a caller in that example.
Thanks for the reply.
You're very kind.

**Comment by Tamimi-amsterdam** [comment]
I have been stuck on this example for 2 days.

` 






        Button b1 = (Button) findViewById(R.id.button1);
        Button b2 = (Button) findViewById(R.id.button2);
        Button b3 = (Button) findViewById(R.id.button3);

        ButtonListener blistener = new ButtonListener();
        b1.setOnClickListener(blistener);
        b2.setOnClickListener(blistener);
        b3.setOnClickListener(blistener);

    }`

It is not working.
can someone help please?

**Comment by tedhagos** [comment]
@Tamimi-amsterdam I think you're referring to Listing 5-19. I may have misplaced this example, it's supposed to be in the section which talks about using an inner class (ButtonHandler) as a listener. Anyway, I've added a new project in chapter 5 (eventhandling-innerclass-as-listener), that should contain the complete source code for Listing 5-19 -- I made a pull request already, so that update on the source code should appear soon. I also made a public gist for it https://gist.github.com/tedhagos/f27e66ecf5661a258c5aa06ea095814b . Let me know if it works for you

**Comment by tedhagos** [comment]
@miltar Hi. Firstly, thanks! I hope you were able to solve the issue already, but just in case you're still having problems, please let me know. It will help greatly also if you could cite the code Listing number on the book.

**Comment by Tamimi-amsterdam** [comment]
@tedhagos Hi,
Thank you for the quick reply. I apologise for the unclear question.
The MainActivity works fine. What did not work in my case was .MainActivity2
Once I do the step in listing 5-21 the program does nothing.

I wonder what did I do wrong.
here's the code from Listing 5-20

`



















package com.example.motamimi.eventhandling1;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Toast;

public class MainActivity2 extends AppCompatActivity
        implements View.OnClickListener {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }



    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.button1:
                show("Button One");
                break;
            case R.id.button2:
                show("Button Two");
                break;
            case R.id.button3:
                show("Button Three");
                break;
            default:
                show("This should not happen");
        }
    }

        void show (String message){
            Toast.makeText(this, message, Toast.LENGTH_LONG).show();
            Log.i(getClass().getName(), message);
        }

    }


`

**Comment by tedhagos** [comment]
@Tamimi-amsterdam nope. You've done nothing wrong, but I did. I should have taken more care with the source codes when I was working on code samples. I may have pruned some parts of the code 
during reformatting/cutting and pasting etc.  There are three missing statements in the `onCreate()` method, after the setContentView statement, here they are

```
    findViewById(R.id.button1).setOnClickListener(this);
    findViewById(R.id.button2).setOnClickListener(this);
    findViewById(R.id.button3).setOnClickListener(this);
```
MainActivity2.java should have looked like this

```
package com.example.ted.eventhandling1;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Toast;

/**
 * Created by ted on 06/10/2017.
 */

public class MainActivity2 extends AppCompatActivity implements View.OnClickListener {

  @Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    findViewById(R.id.button1).setOnClickListener(this);
    findViewById(R.id.button2).setOnClickListener(this);
    findViewById(R.id.button3).setOnClickListener(this);
  }

  @Override
  public void onClick(View view) {
    switch (view.getId()){
      case R.id.button1:
        show("Button One");
        break;
      case R.id.button2:
        show("Button Two");
        break;
      case R.id.button3:
        show("Button Three");
        break;
      default:
        show("This should not happen");
    }
  }
  void show(String message) {
    Toast.makeText(this, message, Toast.LENGTH_LONG).show();
    Log.i(getClass().getName(), message);
  }
}
```

**Comment by Tamimi-amsterdam** [comment]
Thank you very much for the reply and for the book.

**Comment by tedhagos** [comment]
@Tamimi-amsterdam much welcome, thanks for supporting the book.
